# Generated by Django 3.1.7 on 2021-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='awards')),
            ],
            options={
                'verbose_name': 'Сертификат или награда',
                'verbose_name_plural': 'Сертификаты или награды',
            },
        ),
    ]
