# Generated by Django 3.1.7 on 2021-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210421_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='meta_subtitle',
            field=models.CharField(max_length=150, null=True, verbose_name='Вторая часть заголовка сайта (через | )'),
        ),
    ]
