# Generated by Django 3.1.7 on 2021-04-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210422_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='adres',
            name='time',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Время работы'),
        ),
    ]
