# Generated by Django 3.1.7 on 2021-05-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_adres_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фио'),
        ),
    ]
