# Generated by Django 3.1.7 on 2021-04-05 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(upload_to='turn')),
                ('text', models.TextField(verbose_name='Описание услуги')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=300, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(upload_to='services')),
                ('text', models.TextField(verbose_name='Описание')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=300, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='turn.turn')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('text', models.TextField(verbose_name='Прайс')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='turn.turn')),
            ],
            options={
                'verbose_name': 'Прайс',
                'verbose_name_plural': 'Прайсы',
            },
        ),
    ]
