# Generated by Django 3.1.7 on 2021-04-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='description',
            field=models.CharField(max_length=500, null=True, verbose_name='Короткое описание'),
        ),
    ]
