# Generated by Django 3.1.7 on 2021-04-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Servise',
        ),
        migrations.AlterModelOptions(
            name='servise',
            options={'verbose_name': 'Доп.услуга', 'verbose_name_plural': 'Доп.услуги'},
        ),
    ]
