# Generated by Django 3.1.7 on 2021-04-06 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0002_auto_20210405_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servise', to='turn.turn'),
        ),
        migrations.AlterField(
            model_name='servise',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='turn',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
