# Generated by Django 3.1.7 on 2021-04-21 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0002_turn_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('meta_title', models.CharField(max_length=200, verbose_name='Мета заголовок')),
                ('meta_description', models.CharField(max_length=300, verbose_name='Мета описание')),
                ('meta_keywords', models.CharField(max_length=200, verbose_name='Ключевые слова')),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work', to='turn.turn', verbose_name='Работы')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
            },
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='works', verbose_name='Изображение')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='turn.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
