# Generated by Django 3.1.7 on 2021-04-22 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0003_work_workimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='work',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='work',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='workimage',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='turn.work', verbose_name='Работа'),
        ),
    ]
