# Generated by Django 3.1.7 on 2021-04-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0004_auto_20210422_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='servise',
            name='h1',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='turn',
            name='h1',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='turn',
            name='menu_name',
            field=models.CharField(max_length=150, null=True, verbose_name='Текст в меню'),
        ),
    ]
