# Generated by Django 3.1.7 on 2021-04-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turn', '0005_auto_20210422_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servise',
            name='h1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='h1',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='turn',
            name='menu_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Текст в меню'),
        ),
    ]
